version: '3'
services:
    db:
        image: 'postgres:latest'
        environment:
            POSTGRES_PASSWORD: food
            POSTGRES_USER: food
            POSTGRES_DB: food
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"